// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import "./globals.css";
import { NavItem } from "@/components/types";
import Navbar from "@/components/NavBar";
import Footer from "@/components/Footer";

import { Open_Sans } from "next/font/google";
import localFont from "next/font/local";
export const metadata: Metadata = {
  title: "Tuscany Tour",
  description: "Task 7 - Next.js Responsive Design",
};
const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700", "800"], // أوزان الخط الشائعة
  variable: "--font-open-sans", // المتغير الذي سيرتبط بـ CSS
});
const podcast = localFont({
  src: [
    {
      path: "../../public/fonts/Podcast.ttf",
      weight: "400",
      style: "normal",
    }
  ],
  variable: "--font-podcast"
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const mainNavLinks: NavItem[] = [
    { label: 'Home', href: '/' },
    { label: 'About Us', href: '/about' },
    { label: 'Tour Packages', href: '/tours' },
    { label: 'Contact Us', href: '/contact' },
  ];
  const footerData = {
    logoSrc: "assets/logo.png",
    logoAlt: "Tuscany Logo",
    servicesTitle: "Services",
    services: [
      { text: "Bike and Rickshaw rental" },
      { text: "Guided Tours of Lucca" },
      { text: "Guided Bike Tour of Lucca" },
      { text: "Trip In The Tuscan Hills" },
      { text: "Transportation With Luxury Cars" },
      { text: "Wine Tours By Bus With Guide" },
    ],
    homeTitle: "Home",
    homeLinks: [
      { text: "Home", href: "#" },
      { text: "About Us", href: "#" },
      { text: "Tour Packages", href: "#" },
    ],
    helpTitle: "Help",
    helpLinks: [
      { text: "Terms of Use", href: "#" },
      { text: "Privacy Policy", href: "#" },
    ],
    contactsTitle: "Contacts",
    contacts: [
      { icon: "assets/locationfooter.png", text: "Piazza Napoleone, Lucca, Tuscany" },
      { icon: "assets/phone.png", text: "+39 346 368 5708" },
      { icon: "assets/email.png", text: "italiainlimo@gmail.com" },
    ],
    socialTitle: "Social Media",
    socialLinks: [
      { icon: "assets/twitter.png", href: "#", alt: "Twitter" },
      { icon: "assets/facebook.png", href: "#", alt: "Facebook" },
      { icon: "assets/instagram.png", href: "#", alt: "Instagram" },
    ],
    copyrightText: "Copyright © 2022. All rights reserved.",
  };

  return (
    <html lang="en">
      <body className={`${openSans.variable} ${podcast.variable}`}>
        <Navbar
          logoSrc="assets/logo.png"
          navLinks={mainNavLinks}
          signup="Sign Up"
          login="Login"
          logoarrow="assets/arrowbottom.png"
        />
        {children}
        <Footer {...footerData} />
      </body>
    </html>
  );
}